baseurl = "/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = "10"
theme = "PaperMod"
title = "Paddle Board Master"
[Author]
avatar = "img/avatar.png"
bio = "Chris started Paddle boarding in 2018 and got obsessed with it ever since then! In this site i wanted to provide honest reviews of paddleboards. I hope you find my reviews of paddleboards useful."
name = "Chris"
[Params]
authorbox = true
copyright = "PADDLEBOARDMASTER.COM ARE A PARTICIPANT IN THE AMAZON SERVICES LLC ASSOCIATES PROGRAM, AN AFFILIATE ADVERTISING PROGRAM DESIGNED TO PROVIDE A MEANS FOR US TO EARN FEES BY LINKING TO AMAZON.COM AND AFFILIATED SITES."
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
dateformat = "2006-01-02"
description = "Paddleboard Master is the place to find honest reviews about the BEST Paddleboards"
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"
highlightColor = ""
mainSections = ["post", "blog", "news"]
mathjax = true
mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
opengraph = true
pager = true
post_meta = ["author", "date", "categories", "translations"]
readmore = true
schema = true
subtitle = ""
toc = true
twitter_cards = true
[Params.logo]
image = "https://i.ibb.co/JvPMStn/paddleboardlogoicon.png"
subtitle = ""
title = ""
[Params.sidebar]
home = "right"
list = "right"
single = false
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
[Params.style.vars]
fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
highlightColor = "#e22d30"
[Params.thumbnail]
visibility = ["list", "post"]
[Params.widgets]
categories_counter = false
recent_num = 5
tags_counter = false
[Params.widgets.social]
email = "example@example.com"
facebook = "username"
instagram = "username"
twitter = "username"
[[menu.main]]
name = "Buying Guides"
url = "https://paddleboardmaster.com/tags/buying-guides/"
weight = 3
[[menu.main]]
name = "Home"
url = "https://paddleboardmaster.com"
weight = 1
[[menu.main]]
name = "Brands"
url = "https://paddleboardmaster.com/categories/"
weight = 2
